import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'product',
  title: 'Product',
  type: 'document',
  groups: [
    {name: 'identity',     title: 'Identity'},
    {name: 'media',        title: 'Media'},
    {name: 'acoustic',     title: 'Acoustic Specs'},
    {name: 'amplifier',    title: 'Amplifier Specs'},
    {name: 'physical',     title: 'Physical & Finish'},
    {name: 'installation', title: 'Installation'},
    {name: 'connectivity', title: 'Connectivity'},
    {name: 'relations',    title: 'Relationships'},
    {name: 'content',      title: 'Content & Copy'},
    {name: 'seo',          title: 'SEO & GEO'},
  ],
  fields: [

    // ── IDENTITY ───────────────────────────────────────────────────────────
    defineField({name: 'productName',     title: 'Product Name',      type: 'string',  group: 'identity', validation: R => R.required()}),
    defineField({name: 'productFullName', title: 'Full Name',         type: 'string',  group: 'identity'}),
    defineField({name: 'slug',            title: 'Slug',              type: 'slug',    group: 'identity', options: {source: 'productName'}, validation: R => R.required()}),
    defineField({name: 'status',          title: 'Status',            type: 'string',  group: 'identity', options: {list: ['Active','Discontinued','Coming Soon','Internal']}, initialValue: 'Active'}),
    defineField({name: 'launchYear',      title: 'Launch Year',       type: 'number',  group: 'identity'}),
    defineField({name: 'skuBase',         title: 'SKU Base',          type: 'string',  group: 'identity'}),
    defineField({name: 'skuVariants',     title: 'SKU Variants',      type: 'text',    group: 'identity', rows: 3}),
    defineField({name: 'category',        title: 'Category',          type: 'reference', group: 'identity', to: [{type: 'category'}], validation: R => R.required()}),
    defineField({name: 'series',          title: 'Series',            type: 'string',  group: 'identity'}),
    defineField({name: 'subCategory',     title: 'Sub-Category',      type: 'string',  group: 'identity'}),
    defineField({name: 'powerType',       title: 'Power Type',        type: 'string',  group: 'identity', options: {list: ['Passive','Active','Powered']}}),
    defineField({name: 'proprietaryTechBadges', title: 'Proprietary Tech Badges', type: 'string', group: 'identity',
      description: 'Comma-separated: Nano Resonance, PowerDense Dynamics, AeroFrame Chassis, PrecisionXover Array, XS-Flow, PsySculpt'}),

    // ── MEDIA ──────────────────────────────────────────────────────────────
    defineField({
      name: 'heroImage', title: 'Hero Image', type: 'image', group: 'media',
      options: {hotspot: true},
      fields: [{name: 'alt', type: 'string', title: 'Alt text'}],
    }),
    defineField({
      name: 'galleryImages', title: 'Gallery Images', type: 'array', group: 'media',
      of: [{type: 'image', options: {hotspot: true}, fields: [{name: 'alt', type: 'string', title: 'Alt text'}]}],
    }),
    defineField({
      name: 'lifestyleImages', title: 'Lifestyle Images', type: 'array', group: 'media',
      of: [{type: 'image', options: {hotspot: true}, fields: [{name: 'alt', type: 'string', title: 'Alt text'}]}],
    }),
    defineField({
      name: 'installationDiagramImages', title: 'Installation Diagram Images', type: 'array', group: 'media',
      of: [{type: 'image', options: {hotspot: true}, fields: [{name: 'alt', type: 'string', title: 'Label'}]}],
    }),
    defineField({
      name: 'heroVideoFile', title: 'Hero Video File', type: 'file', group: 'media',
      description: 'Upload MP4 directly. Takes priority over Hero Video URL.',
      options: { accept: 'video/*' },
    }),
    defineField({
      name: 'heroVideo', title: 'Hero Video URL', type: 'url', group: 'media',
      description: 'YouTube or Vimeo URL. Autoplays muted in hero section.',
    }),
    defineField({
      name: 'productVideos', title: 'Product Videos', type: 'array', group: 'media',
      description: 'Lifestyle and demo videos shown in the gallery',
      of: [{
        type: 'object',
        name: 'productVideo',
        fields: [
          {name: 'videoFile', title: 'Video File (MP4)',   type: 'file', options: { accept: 'video/*' }},
          {name: 'url',       title: 'Video URL',        type: 'url'},
          {name: 'title',     title: 'Title',            type: 'string'},
          {name: 'type',      title: 'Type',             type: 'string', options: {list: ['lifestyle','demo','review']}},
          {name: 'thumbnail', title: 'Custom Thumbnail', type: 'image'},
        ],
        preview: {select: {title: 'title', subtitle: 'type'}},
      }],
    }),
    defineField({name: 'model3dUrl', title: '3D Model Path', type: 'string', group: 'media',
      description: 'Relative path e.g. /models/cane.glb — place GLB in web/public/models/'}),
    defineField({name: 'hasArView', title: 'AR View Available', type: 'boolean', group: 'media', initialValue: false}),

    // ── ACOUSTIC SPECS ─────────────────────────────────────────────────────
    defineField({name: 'powerRmsW',       title: 'Power RMS (W)',            type: 'number', group: 'acoustic'}),
    defineField({name: 'powerPeakW',      title: 'Power Peak (W)',           type: 'number', group: 'acoustic'}),
    defineField({name: 'impedanceOhms',   title: 'Impedance (Ohms)',         type: 'number', group: 'acoustic'}),
    defineField({name: 'sensitivityDb',   title: 'Sensitivity (dB)',         type: 'number', group: 'acoustic'}),
    defineField({name: 'splMaxDb',        title: 'Max SPL (dB)',             type: 'number', group: 'acoustic', description: 'Sensitivity + 10×log10(Peak Power W)' }),
    defineField({name: 'freqLowHz',       title: 'Freq Low (Hz)',            type: 'number', group: 'acoustic'}),
    defineField({name: 'freqHighHz',      title: 'Freq High (Hz)',           type: 'number', group: 'acoustic'}),
    defineField({name: 'freqQualifier',   title: 'Freq Qualifier',           type: 'string', group: 'acoustic', description: 'e.g. +/-3dB'}),
    defineField({name: 'driverCount',     title: 'Driver Count',             type: 'number', group: 'acoustic'}),
    defineField({name: 'driverSize',      title: 'Driver Size',              type: 'string', group: 'acoustic'}),
    defineField({name: 'driverMaterial',  title: 'Driver Material',          type: 'string', group: 'acoustic'}),
    defineField({name: 'driverDescription', title: 'Driver Description',     type: 'string', group: 'acoustic'}),
    defineField({name: 'tweeterCount',    title: 'Tweeter Count',            type: 'number', group: 'acoustic'}),
    defineField({name: 'tweeterSize',     title: 'Tweeter Size',             type: 'string', group: 'acoustic'}),
    defineField({name: 'tweeterMaterial', title: 'Tweeter Material',         type: 'string', group: 'acoustic'}),
    defineField({name: 'tweeterAimable',  title: 'Aimable Tweeter',          type: 'boolean',group: 'acoustic', initialValue: false}),
    defineField({name: 'crossoverType',   title: 'Crossover Type',           type: 'string', group: 'acoustic'}),
    defineField({name: 'crossoverFrequency', title: 'Crossover Frequency',   type: 'string', group: 'acoustic'}),
    defineField({name: 'recommendedCrossoverHz', title: 'Recommended Crossover (Hz)', type: 'number', group: 'acoustic'}),
    defineField({name: 'directivityHDeg',title: 'Horizontal Directivity (deg)', type: 'number', group: 'acoustic'}),
    defineField({name: 'directivityVDeg',title: 'Vertical Directivity (deg)',   type: 'number', group: 'acoustic'}),
    defineField({name: 'eqData',          title: 'EQ Data (CSV)',            type: 'text',   group: 'acoustic', rows: 6,
      description: 'CSV: freq,gain,type,q'}),
    defineField({name: 'eqProfileName',   title: 'EQ Profile Name',          type: 'string', group: 'acoustic'}),
    defineField({name: 'typicalUseCases', title: 'Typical Use Cases',        type: 'string', group: 'acoustic',
      description: 'e.g. Living Room, Home Cinema, Restaurant'}),
    defineField({name: 'minRoomVolume',   title: 'Min Room Volume (m3)',     type: 'number', group: 'acoustic'}),
    defineField({name: 'maxRoomVolume',   title: 'Max Room Volume (m3)',     type: 'number', group: 'acoustic'}),
    defineField({name: 'recommendedRoomSize', title: 'Recommended Room Size', type: 'string', group: 'acoustic'}),

    // ── AMPLIFIER / POWERED ────────────────────────────────────────────────
    defineField({name: 'totalPowerW',        title: 'Total Power (W)',       type: 'number', group: 'amplifier'}),
    defineField({name: 'channelCount',       title: 'Channel Count',         type: 'number', group: 'amplifier'}),
    defineField({name: 'powerPerCh8OhmW',    title: 'Power/Ch @ 8 Ohm (W)', type: 'number', group: 'amplifier'}),
    defineField({name: 'powerPerCh4OhmW',    title: 'Power/Ch @ 4 Ohm (W)', type: 'number', group: 'amplifier'}),
    defineField({name: 'ampClass',           title: 'Amp Class',             type: 'string', group: 'amplifier', options: {list: ['Class A','Class AB','Class D','Class H']}}),
    defineField({name: 'thdN',               title: 'THD+N',                 type: 'string', group: 'amplifier'}),
    defineField({name: 'snrDb',              title: 'SNR (dB)',              type: 'string', group: 'amplifier'}),
    defineField({name: 'inputSensitivity',   title: 'Input Sensitivity',     type: 'string', group: 'amplifier'}),
    defineField({name: 'inputImpedance',     title: 'Input Impedance',       type: 'string', group: 'amplifier'}),
    defineField({name: 'freqResponse',       title: 'Freq Response',         type: 'string', group: 'amplifier'}),
    defineField({name: 'hasDsp',             title: 'Has DSP',               type: 'boolean',group: 'amplifier', initialValue: false}),
    defineField({name: 'dspProcessorSpec',   title: 'DSP Processor',         type: 'string', group: 'amplifier'}),
    defineField({name: 'hasStreamer',         title: 'Has Streamer',          type: 'boolean',group: 'amplifier', initialValue: false}),
    defineField({name: 'streamingProtocols', title: 'Streaming Protocols',   type: 'string', group: 'amplifier'}),
    defineField({name: 'protectionFeatures', title: 'Protection Features',   type: 'string', group: 'amplifier'}),
    defineField({name: 'rackMountable',      title: 'Rack Mountable',        type: 'boolean',group: 'amplifier', initialValue: false}),
    defineField({name: 'rackUnitSize',       title: 'Rack Unit Size',        type: 'string', group: 'amplifier'}),

    // ── PHYSICAL & FINISH ──────────────────────────────────────────────────
    defineField({name: 'heightMm',          title: 'Height (mm)',            type: 'number', group: 'physical'}),
    defineField({name: 'widthMm',           title: 'Width (mm)',             type: 'number', group: 'physical'}),
    defineField({name: 'depthMm',           title: 'Depth (mm)',             type: 'number', group: 'physical'}),
    defineField({name: 'diameterMm',        title: 'Diameter (mm)',          type: 'number', group: 'physical'}),
    defineField({name: 'weightKg',          title: 'Weight (kg)',            type: 'number', group: 'physical'}),
    defineField({name: 'housingMaterial',   title: 'Housing Material',       type: 'string', group: 'physical'}),
    defineField({name: 'paintFinish',       title: 'Paint / Finish Type',    type: 'string', group: 'physical', options: {list: ['Anodised','Powder Coat','Primed','Wet Paint','Matte','Gloss']}}),
    defineField({name: 'colorsStandard',    title: 'Standard Colours',       type: 'string', group: 'physical'}),
    defineField({name: 'finishOptions',     title: 'Finish Options',         type: 'string', group: 'physical'}),
    defineField({name: 'customRalAvailable',title: 'Custom RAL Available',   type: 'boolean',group: 'physical', initialValue: false}),
    defineField({name: 'customRalMoq',      title: 'Custom RAL MOQ',         type: 'string', group: 'physical'}),
    defineField({name: 'paintableGrille',   title: 'Paintable Grille',       type: 'boolean',group: 'physical', initialValue: false}),
    defineField({name: 'grilleIncluded',    title: 'Grille Included',        type: 'boolean',group: 'physical', initialValue: true}),
    defineField({name: 'grilleMaterial',    title: 'Grille Material',        type: 'string', group: 'physical'}),
    defineField({name: 'ipRating',          title: 'IP Rating',              type: 'string', group: 'physical'}),
    defineField({name: 'marineTreatable',   title: 'Marine Treatable',       type: 'boolean',group: 'physical', initialValue: false}),
    defineField({name: 'fireRating',        title: 'Fire Rating',            type: 'string', group: 'physical'}),
    defineField({name: 'certifications',    title: 'Certifications',         type: 'string', group: 'physical',
      description: 'e.g. CE, FCC, RoHS, UKCA'}),

    // ── INSTALLATION ───────────────────────────────────────────────────────
    defineField({name: 'cutoutHeightMm',    title: 'Cutout Height (mm)',      type: 'number', group: 'installation'}),
    defineField({name: 'cutoutWidthMm',     title: 'Cutout Width (mm)',       type: 'number', group: 'installation'}),
    defineField({name: 'cutoutDiameterMm',  title: 'Cutout Diameter (mm)',   type: 'number', group: 'installation'}),
    defineField({name: 'requiredCavityDepthMm', title: 'Cavity Depth (mm)',  type: 'number', group: 'installation'}),
    defineField({name: 'mountingMethods',   title: 'Mounting Methods',       type: 'text',   group: 'installation', rows: 3}),
    defineField({name: 'mountingBracketRequired', title: 'Mounting Bracket Required', type: 'boolean', group: 'installation', initialValue: false}),
    defineField({name: 'backBoxRequired',   title: 'Back Box Required',      type: 'boolean',group: 'installation', initialValue: false}),
    defineField({name: 'backBoxIncluded',   title: 'Back Box Included',      type: 'boolean',group: 'installation', initialValue: false}),
    defineField({name: 'installationOrientation', title: 'Orientation',      type: 'string', group: 'installation', options: {list: ['Vertical','Horizontal','Either']}}),
    defineField({name: 'screwSize',         title: 'Screw Size',             type: 'string', group: 'installation'}),
    defineField({name: 'wireGaugeRecommended', title: 'Wire Gauge',          type: 'string', group: 'installation'}),
    defineField({name: 'wireConnectorType', title: 'Wire Connector Type',    type: 'string', group: 'installation'}),
    defineField({name: 'speakerWireConnector', title: 'Speaker Connector',   type: 'string', group: 'installation'}),
    defineField({name: 'minRiggingHeight',  title: 'Min Rigging Height',     type: 'string', group: 'installation'}),
    defineField({name: 'minSpeakerSpacing', title: 'Min Speaker Spacing',    type: 'string', group: 'installation'}),
    defineField({name: 'itemsInBox',        title: 'Items in Box',           type: 'text',   group: 'installation', rows: 4,
      description: 'One item per line'}),
    defineField({name: 'installationSteps', title: 'Installation Steps',     type: 'text',   group: 'installation', rows: 8,
      description: 'Numbered steps for the auto-generated install manual'}),
    defineField({name: 'positioningNote',   title: 'Positioning Note',       type: 'text',   group: 'installation', rows: 3}),

    // ── NEW: Installation manual fields ────────────────────────────────────
    defineField({
      name: 'installationType',
      title: 'Installation Type',
      type: 'string',
      group: 'installation',
      description: 'Drives the auto-generated installation manual template.',
      options: {
        list: [
          {title: 'Keyhole Wall Mount (Bonsai, Cane, QuadCane)',              value: 'keyhole-wall'},
          {title: 'Bracket Wall Mount (Cedar, Camphor 6, Camphor 8)',         value: 'bracket-wall'},
          {title: 'Ceiling — Circular Cutout (Aspen 6, Aspen 8, Aster 6)',   value: 'ceiling-circular'},
          {title: 'Ceiling — Rectangular Cutout (Ghost 2.0)',                 value: 'ceiling-rectangular'},
          {title: 'In-Wall — Dog-leg Clips (Bergenia, Sage, Oak, Willow)',    value: 'inwall-dogleg'},
          {title: 'In-Wall — Spring Clips (Bonsai IC, Cane IC, QuadCane IC)', value: 'inwall-springclip'},
          {title: 'In-Wall Subwoofer (Acacia 6 IW, Acacia 10 IW)',           value: 'inwall-sub'},
          {title: 'Banyan Canopy',                                             value: 'banyan-canopy'},
          {title: 'Banyan Pith',                                               value: 'banyan-pith'},
          {title: 'Spirea Landscape',                                          value: 'spirea'},
          {title: 'Powered Subwoofer (Juniper, Acacia PW)',                   value: 'powered-sub'},
          {title: 'Passive Subwoofer (Acacia Std)',                           value: 'passive-sub'},
          {title: 'DSP Amplifier (Root 4, Xylem, Lucifer)',                   value: 'dsp-amplifier'},
          {title: 'Streaming Amplifier (Air Amp)',                             value: 'streaming-amplifier'},
          {title: 'Streamer (Air Mini)',                                        value: 'streamer'},
        ],
      },
    }),
    defineField({
      name: 'screwSpacingMm',
      title: 'Screw / Keyhole Spacing (mm)',
      type: 'number',
      group: 'installation',
      description: 'Centre-to-centre distance between mounting screws or keyhole slots. Bonsai: 11.74 | Cane: 82 | QuadCane: 82 | Cedar: 120 | Camphor 6: 138 | Camphor 8: 227',
    }),
    defineField({
      name: 'ioPortsImage',
      title: 'I/O Ports Diagram / Back Panel Image',
      type: 'image',
      group: 'installation',
      options: {hotspot: true},
      description: 'Photo or diagram of the rear panel with all ports labelled. Used in amplifier and powered sub manuals.',
    }),
    defineField({
      name: 'installManualRef',
      title: 'Install Manual Asset Ref (auto)',
      type: 'string',
      group: 'installation',
      description: 'Auto-populated cache key — clear to regenerate',
    }),
    defineField({
      name: 'installManualHash',
      title: 'Install Manual Hash (auto)',
      type: 'string',
      group: 'installation',
      description: 'Auto-populated — clear to force PDF regeneration',
    }),

    // ── CONNECTIVITY ───────────────────────────────────────────────────────
    defineField({name: 'inputs',               title: 'Inputs',              type: 'string', group: 'connectivity'}),
    defineField({name: 'outputs',              title: 'Outputs',             type: 'string', group: 'connectivity'}),
    defineField({name: 'communicationPorts',   title: 'Communication Ports', type: 'string', group: 'connectivity'}),
    defineField({name: 'wirelessConnectivity', title: 'Wireless',            type: 'string', group: 'connectivity'}),
    defineField({name: 'networkProtocol',      title: 'Network Protocol',    type: 'string', group: 'connectivity'}),
    defineField({name: 'controlProtocol',      title: 'Control Protocol',    type: 'string', group: 'connectivity'}),
    defineField({name: 'compatibleControlSystems', title: 'Compatible Control Systems', type: 'string', group: 'connectivity',
      description: 'e.g. Savant, Control4, Crestron'}),
    defineField({name: 'mobileAppName',        title: 'Mobile App Name',     type: 'string', group: 'connectivity'}),
    defineField({name: 'mobileAppLinkIos',     title: 'iOS App Link',        type: 'url',    group: 'connectivity'}),
    defineField({name: 'mobileAppLinkAndroid', title: 'Android App Link',    type: 'url',    group: 'connectivity'}),
    defineField({name: 'desktopSoftwareName',  title: 'Desktop Software',    type: 'string', group: 'connectivity'}),
    defineField({name: 'desktopSoftwareUrl',   title: 'Desktop Software URL',type: 'url',    group: 'connectivity'}),

    // ── RELATIONSHIPS ──────────────────────────────────────────────────────
    defineField({name: 'recommendedPairingPrimary', title: 'Primary Pairing', type: 'reference', group: 'relations',
      to: [{type: 'product'}]}),
    defineField({name: 'recommendedPairingSecondary', title: 'Secondary Pairing', type: 'reference', group: 'relations',
      to: [{type: 'product'}]}),
    defineField({name: 'compatibleAmplifiers', title: 'Compatible Amplifiers', type: 'array', group: 'relations',
      of: [{type: 'reference', to: [{type: 'product'}]}]}),
    defineField({name: 'compatibleSubwoofers', title: 'Compatible Subwoofers', type: 'array', group: 'relations',
      of: [{type: 'reference', to: [{type: 'product'}]}]}),
    defineField({name: 'compatibleSpeakers',   title: 'Compatible Speakers',   type: 'array', group: 'relations',
      of: [{type: 'reference', to: [{type: 'product'}]}]}),
    defineField({name: 'accessories',          title: 'Accessories & Mounts',  type: 'array', group: 'relations',
      description: 'Corner mounts, floor stands, grilles, brackets',
      of: [{type: 'reference', to: [{type: 'product'}]}]}),
    defineField({name: 'relatedProducts',      title: 'Related Products',      type: 'array', group: 'relations',
      description: 'Alternatives in same category',
      of: [{type: 'reference', to: [{type: 'product'}]}]}),
    defineField({
      name: 'typicalSetups',
      title: 'Typical Setups',
      type: 'array',
      group: 'relations',
      description: 'Common installation packages featuring this product',
      of: [{
        type: 'object',
        name: 'setup',
        title: 'Setup',
        fields: [
          defineField({name: 'label', title: 'Setup Label', type: 'string',
            description: 'e.g. 2.1 TV Setup, Home Cinema 5.1'}),
          defineField({name: 'description', title: 'Short Description', type: 'string'}),
          defineField({
            name: 'products',
            title: 'Products in Setup',
            type: 'array',
            of: [{
              type: 'object',
              name: 'setupProduct',
              fields: [
                defineField({name: 'product', title: 'Product', type: 'reference', to: [{type: 'product'}]}),
                defineField({name: 'quantity', title: 'Quantity', type: 'number'}),
                defineField({name: 'role', title: 'Role', type: 'string',
                  description: 'e.g. LR Speakers, Subwoofer, Amplifier'}),
              ],
              preview: {
                select: { title: 'product.productName', qty: 'quantity', role: 'role' },
                prepare: ({title, qty, role}) => ({ title: `${title} ×${qty}`, subtitle: role })
              }
            }]
          }),
        ],
        preview: {
          select: { title: 'label', desc: 'description' },
          prepare: ({title, desc}) => ({ title, subtitle: desc })
        }
      }]
    }),
    defineField({name: 'brochure', title: 'Product Brochure PDF', type: 'file', group: 'media',
      description: 'Auto-generated — delete this file to force regeneration on next request',
      options: { accept: 'application/pdf' }}),
    defineField({name: 'brochureRef', title: 'Brochure Asset Ref (legacy)', type: 'string', group: 'media',
      description: 'Auto-populated cache key — clear to regenerate'}),
    defineField({name: 'brochureHash', title: 'Brochure Hash', type: 'string', group: 'media',
      description: 'Auto-populated — hash used to detect stale cache'}),
    defineField({name: 'specSheetHash',  title: 'Spec Sheet Hash (auto)',  type: 'string', group: 'relations',
      description: 'Auto-generated hash of spec data. Delete to force PDF regeneration.', readOnly: true}),
    defineField({name: 'specSheet',   title: 'Spec Sheet (PDF)',      type: 'file',  group: 'relations', options: {accept: 'application/pdf'}}),
    defineField({name: 'installGuide', title: 'Installation Guide (PDF)', type: 'file', group: 'relations', options: {accept: 'application/pdf'}}),
    defineField({name: 'cadFile',              title: 'CAD File (DWG/DXF)',    type: 'file',  group: 'relations'}),

    // ── CONTENT & COPY ─────────────────────────────────────────────────────
    defineField({name: 'tagline',          title: 'Tagline',            type: 'string', group: 'content'}),
    defineField({name: 'shortDescription', title: 'Short Description',  type: 'text',   group: 'content', rows: 3}),
    defineField({name: 'longDescription',  title: 'Long Description',   type: 'array',  group: 'content', of: [{type: 'block'}]}),
    defineField({name: 'applicationNotes', title: 'Application Notes',  type: 'text',   group: 'content', rows: 3}),

    // ── SEO & GEO ──────────────────────────────────────────────────────────
    defineField({name: 'seoTitle',       title: 'SEO Title',           type: 'string', group: 'seo',
      description: 'Max 60 chars. Defaults to product name + XSCACE.',
      validation: R => R.max(60)}),
    defineField({name: 'seoDescription', title: 'SEO Description',     type: 'text',   group: 'seo', rows: 3,
      description: '120-160 chars. Shown in Google results.',
      validation: R => R.max(160)}),
    defineField({name: 'seoKeywords',    title: 'SEO Keywords',        type: 'string', group: 'seo',
      description: 'Comma-separated: architectural speaker, in-wall speaker, slim speaker UK'}),
    defineField({name: 'ogImage',        title: 'Open Graph Image',    type: 'image',  group: 'seo',
      description: '1200x630px. Shown when shared on social. Defaults to heroImage.'}),
    defineField({name: 'geoDescription', title: 'GEO Description (for AI search)', type: 'text', group: 'seo', rows: 4,
      description: 'Plain factual text for AI search engines (Perplexity, ChatGPT, Gemini). Include dimensions, specs, use cases.'}),
    defineField({name: 'targetRegions',  title: 'Target Regions',      type: 'string', group: 'seo',
      description: 'Comma-separated: UK, India, Philippines, Australia, Canada'}),
    defineField({name: 'targetApplications', title: 'Target Applications', type: 'string', group: 'seo',
      description: 'Comma-separated: Residential, Hospitality, Marine, Commercial, Home Cinema'}),

  ],

  preview: {
    select: {
      title: 'productName',
      subtitle: 'series',
      media: 'heroImage',
    },
    prepare({title, subtitle, media}) {
      return {title: title || 'Untitled', subtitle: subtitle || '', media}
    },
  },
})
